backend/portey_road/urls.py
"""portey_road URL Configuration

The `urlpatterns` list routes URLs to view. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function view
    1. Add an import:  from my_app import view
    2. Add a URL to urlpatterns:  path('', view.home, name='home')
Class-based view
    1. Add an import:  from other_app.view import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.utils import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.utils'))
"""
from django.contrib import admin
from django.urls import *

urlpatterns = [
    path('admin/', admin.site.urls),
    # 配置根路由 我们一般都使用namespace所以include里第一个参数是元组（指定子路由，子应用名）
    re_path('^', include('apps.userapp.urls')),
    re_path('^', include(('apps.newsapp.urls', 'apps.newsapp'), namespace='newsapp')),
    re_path('^', include(('apps.verifications.urls', 'apps.verifications'), namespace='verifications')),
    re_path('^', include('apps.oauth.urls')),
    re_path('^', include('apps.payment.urls'), ),
    re_path('^', include('apps.mg_admin.urls')),


]

backend/apps/newsapp/models.py
from django.db import models

from apps.userapp.models import Users
from utils.basemodels import BaseModel


class NewsChannel(BaseModel):
    """诗路频道"""

    name = models.CharField(max_length=30, unique=True, verbose_name='频道名称')
    url = models.CharField(default='', null=True, blank=True, max_length=50,
                           verbose_name='频道⻚⾯链接')

    class Meta:
        db_table = 't_news_channel'
        verbose_name = '诗路频道'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class NewsCategory(BaseModel):
    """诗路类别"""

    name = models.CharField(max_length=10, verbose_name='名称')
    sequence = models.IntegerField(verbose_name='排序')
    channel = models.ForeignKey(NewsChannel, on_delete=models.PROTECT)

    class Meta:
        db_table = 't_news_category'
        verbose_name = '诗路类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Article(BaseModel):
    """⽂章"""

    title = models.CharField(max_length=100, unique=True, verbose_name='⽂章标题')
    content = models.TextField(verbose_name='⽂章内容')
    default_img = models.ImageField(verbose_name='⾸⻚图⽚')
    starcount = models.IntegerField(default=0, verbose_name='点赞量')
    commentcount = models.IntegerField(default=0, verbose_name='评论量')
    category = models.ForeignKey(NewsCategory, on_delete=models.PROTECT,
                                 verbose_name='从属类别')
    channel = models.ForeignKey(NewsChannel, on_delete=models.PROTECT, verbose_name='从属诗路')

    class Meta:
        db_table = 't_news_article'
        verbose_name = '⽂章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class ArticleImage(BaseModel):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    image = models.ImageField(verbose_name='图⽚')

    class Meta:
        db_table = 't_article_image'
        verbose_name = 'article图⽚'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.article.title, self.id)


class Comment(BaseModel):
    article = models.ForeignKey(Article, on_delete=models.DO_NOTHING, verbose_name='评论文章')
    comment_content = models.TextField(verbose_name='评论文章')
    comment_author = models.ForeignKey(Users, on_delete=models.DO_NOTHING, verbose_name='评论人')
    comment_time = models.DateTimeField(auto_now_add=True, verbose_name='评论时间')
    pre_comment = models.ForeignKey('self', on_delete=models.DO_NOTHING, null=True, verbose_name='父评论id')

    class Meta:
        db_table = 't_comment'
        verbose_name = '评论表'
        verbose_name_plural = verbose_name

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %} {% endblock title %}</title>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" type="image/x-icon" href="/static/images/favicon.ico"/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="/static/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/css/font-awesome.min.css">
	<link rel="stylesheet" href="/static/css/owl.carousel.min.css">
	<link rel="stylesheet" href="/static/css/animate.min.css">
	<link rel="stylesheet" href="/static/css/jquery-ui.css">
	<link rel="stylesheet" href="/static/css/slick.css">
	<link rel="stylesheet" href="/static/css/chosen.min.css">
	<link rel="stylesheet" href="/static/css/pe-icon-7-stroke.css">
	<link rel="stylesheet" href="/static/css/magnific-popup.min.css">
	<link rel="stylesheet" href="/static/css/lightbox.min.css">
	<link rel="stylesheet" href="/static/js/fancybox/source/jquery.fancybox.css">
	<link rel="stylesheet" href="/static/css/jquery.scrollbar.min.css">
	<link rel="stylesheet" href="/static/css/mobile-menu.css">
	<link rel="stylesheet" href="/static/fonts/flaticon/flaticon.css">
	<link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/icon/iconfont.css">
    <script src="/static/js/vue.js"></script>
    <script src="/static/js/common.js"></script>
    <style>
        #background{
            border: medium none;
        }
    </style>

{#    <script src="https://eqcn.ajz.miesnfu.com/wp-content/plugins/wp-3d-pony/live2dw/lib/L2Dwidget.min.js"></script>#}
{#    <script>#}
{#        L2Dwidget.init({#}
{#            "model": { "jsonPath":"https://unpkg.com/live2d-widget-model-chitose@1.0.5/assets/chitose.model.json", "scale": 1, "hHeadPos":0.5, "vHeadPos":0.618 },#}
{#            "display": { "position": "right", "width": 200, "height": 250, "hOffset": -50, "vOffset": 0 },#}
{#            "mobile": { "show": true, "scale": 0.7 },#}
{#            "react": { "opacityDefault": 0.7, "opacityOnHover": 0.2 }#}
{#        });#}
{#    </script>#}

    {% block css %}

    {% endblock css %}
</head>
<body class="inblog-page">




    {% block header %}

    <header class="header style7">
		<div class="top-bar">
			<div class="container">
				<div class="top-bar-left">
					<div class="header-message">
                        欢迎来到 诗路浙江！

					</div>
				</div>
				<div class="top-bar-right">

					<ul class="header-user-links">
                    {% if user %}
                        {% if user.username %}
                            欢迎您！<a href="/usercenter/"><span style="font-weight: bolder;">[ {{ user.username }} ]</span></a>
                            &emsp;<a href="/logout/">退出登录</a>&nbsp;
                            {% else %}
                            <li>
                                <a href="/login/">登录</a>&nbsp;&nbsp;&nbsp;
                                <a href="/register/">注册</a>
                            </li>
                        {% endif %}
                    {% endif %}

					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="main-header">
				<div class="row">
					<div class="col-lg-3 col-sm-4 col-md-3 col-xs-7 col-ts-12 header-element">
						<div class="logo">
							<a href="/">
								<img src="/static/images/img.png" alt="img">
							</a>
						</div>
					</div>
					<div class="col-lg-7 col-sm-8 col-md-6 col-xs-5 col-ts-12">
						<div class="block-search-block">
							<form action="/search/" method="get" class="form-search form-search-width-category">
								<div class="form-content">
									<div class="inner">
										<input type="text" class="input" name="q" value="" placeholder="搜索站内资讯">
									</div>
									<button class="btn-search" type="submit">
										<span class="icon-search"></span>
									</button>

								</div>
							</form>

						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="header-nav-container">
			<div class="container">
				<div class="header-nav-wapper main-menu-wapper">

					<div class="header-nav">
						<div class="container-wapper">
							<ul class="teamo-clone-mobile-menu teamo-nav main-menu " id="menu-main-menu">

                                {% for channel in channels %}
                                    <li class="menu-item m-active">
                                        <a  style="font-weight: normal;font-size: 16px;" href={{ channel.url }} >{{ channel.name }}</a>
                                    </li>
                                {% endfor %}

								<li class="menu-item">
									<a style="font-weight: normal;font-size: 16px;" href="https://baike.baidu.com/item/%E8%AF%97%E7%94%BB%E6%B5%99%E6%B1%9F/24183027" class="teamo-menu-item-title"  >更多</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>


{% endblock header %}



    {% block content %}

        <div class="main-content main-content-blog list left-sidebar">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcrumb-trail breadcrumbs">
						<ul class="trail-items breadcrumb">

						</ul>
					</div>
				</div>
			</div>
			<div class="row">
{#            <iframe id="background" style="height: 600px;#}
{#                            width: 250px;#}
{#                            margin-left: -100px;#}
{#                            margin-right: -200px;#}
                            {#margin-top: -100px;#}
{#                    float: right;#}
{#                            top: 500px;" src="/static/js/three.js/examples/webgl_loader_mmd2.html"></iframe>#}
                {% block rightcontent %}

                {% endblock rightcontent %}



                {# 侧边栏开始#}


                <div class="sidebar sidebar-blog col-lg-3 col-md-4 col-sm-12 col-xs-12">
                <div class="wrapper-sidebar">

                    <div class="widget widget-categories">
                        <h3 class="widgettitle"></h3>
                        <ul class="list-categories">
                            <li><a href="#">全部</a></li>
                            {% for category in channels[2].newscategory_set.all() %}
                                <li><a href={{ channels[0].url }}>{{ category.name }}</a></li>
                            {% endfor %}


                        </ul>
                    </div>
                    <div class="widget widget-post">
                        <h3 class="widgettitle">诗路文化</h3>
                        <ul class="teamo-posts">
                            <li class="widget-post-item">
                                <div class="thumb-blog">
                                    <img src="/static/images/img_1.png" alt="img">
                                </div>
                                <div class="post-content">
                                    <div class="cat">
                                    </div>
                                    <h5 class="post-title"><a href="https://baike.baidu.com/item/%E8%AF%97%E8%B7%AF%E6%96%87%E5%8C%96%E5%B8%A6/24191157">浙江诗路文化带 <span>[...]</span></a></h5>
                                </div>
                            </li>
                            <li class="widget-post-item">
                                <div class="thumb-blog">
                                    <img src="/static/images/img_2.png" alt="img">
                                </div>
                                <div class="post-content">
                                    <div class="cat">
                                    </div>
                                    <h5 class="post-title"><a href="https://baijiahao.baidu.com/s?id=1695223390502423348">瓯江山水诗路 <span>[...]</span></a></h5>
                                </div>
                            </li>
                            <li class="widget-post-item">
                                <div class="thumb-blog">
                                    <img src="/static/images/img_3.png" alt="img">
                                </div>
                                <div class="post-content">
                                    <div class="cat">
                                    </div>
                                    <h5 class="post-title"><a href="https://www.zj.gov.cn/art/2020/11/4/art_1229352121_59040754.html">诗路文化主题活动 <span>[...]</span></a></h5>
                                </div>
                            </li>

                        </ul>
                    </div>

                </div>
            </div>

            {# 侧边栏结束#}
            <iframe id="background" style="height: 620px;
                            width: 400px;
                            margin-left: -100px;
                            margin-right: 100px;
                            margin-top: -550px;
                    {#float: left;#}
                            top: 500px;" src="/static/js/three.js/examples/webgl_loader_md2.html"></iframe>

            </div>
		</div>
	</div>
        

    {% endblock  content %}



    
    {% block footer %}

        <footer class="footer style7">
		<div class="container">
			<div class="container-wapper">
				<div class="footer-end">
					<div class="row">
						<div class="col-sm-12 col-xs-12">
							<div class="coppyright">Copyright © 2020.Company name All rights reserved.
                                <span>
                                    <a class="tight" href="http://www.cuz.edu.cn/" target="_blank" rel="nofollow">诗路传媒 有你同行 </a>
                                </span>
                            </div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

    {% endblock  footer %}
    



    <script src="/static/js/axios-0.18.0.min.js"></script>
	<script src="/static/js/jquery-1.12.4.min.js"></script>
	<script src="/static/js/jquery.plugin-countdown.min.js"></script>
	<script src="/static/js/jquery-countdown.min.js"></script>
	<script src="/static/js/bootstrap.min.js"></script>
	<script src="/static/js/owl.carousel.min.js"></script>
	<script src="/static/js/magnific-popup.min.js"></script>
	<script src="/static/js/isotope.min.js"></script>
	<script src="/static/js/jquery.scrollbar.min.js"></script>
	<script src="/static/js/jquery-ui.min.js"></script>
	<script src="/static/js/mobile-menu.js"></script>
	<script src="/static/js/chosen.min.js"></script>
	<script src="/static/js/slick.js"></script>
	<script src="/static/js/jquery.elevateZoom.min.js"></script>
	<script src="/static/js/jquery.actual.min.js"></script>
	<script src="/static/js/fancybox/source/jquery.fancybox.js"></script>
	<script src="/static/js/lightbox.min.js"></script>
	<script src="/static/js/owl.thumbs.min.js"></script>
	<script src="/static/js/jquery.scrollbar.min.js"></script>
	<script src="/static/js/frontend-plugin.js"></script>

    {% block js %}

        <script>
            function menu_over(ele) {

                ele.style.backgroundColor = 'lightgreen';
            }

            function menu_out(ele) {
                ele.style.backgroundColor = '';
            }


        </script>


    {% endblock  js %}
</body>
</html>